export enum ActionTypes {
  REQUEST_GROUP = 'REQUEST_GROUP',
  SUCCESS_GROUP = 'SUCCESS_GROUP',
  ERROR_GROUP = 'ERROR_GROUP',
  REQUEST_NEWLY_GROUP = 'REQUEST_NEWLY_GROUP',
  SUCCESS_NEWLY_GROUP = 'SUCCESS_NEWLY_GROUP',
  ERROR_NEWLY_GROUP = 'ERROR_NEWLY_GROUP'
}
